### ISSUE TITLE
report bugs

### ISSUE THREAD

**Issue by Gavin-23** [markxiaotao/03Restaurant#1]
1. Telephone number in other pages are not yet updated.

**Comment by Gavin-23** [comment]
2. Find 3 new photos to replace the slideshow in the front page.

**Comment by Gavin-23** [comment]
3. At the main course section, we no longer serve Vegetarian and Poultry dishes.

**Comment by Gavin-23** [comment]
4. Prices shown in the entire sites are not in a correct currency, replace £ with $. (Priority = High)

**Comment by Gavin-23** [comment]
5. The 2FOR12012 code does not have a proper description. Please tell the customer that it is a coupon
code and can be redeemed only on site. Also change the year to 2018.

**Comment by markxiaotao** [comment]
Good job

**Comment by Gavin-23** [comment]
thanks!!!
