### ISSUE TITLE
The 2FOR12012 code does not have a proper description. Please tell the customer that it is a coupon code and can be redeemed only on site. Also change the year to 2018.

### ISSUE THREAD

**Issue by Gavin-23** [markxiaotao/03Restaurant#12]
in the Specialoffers.html, The 2FOR12012 code does not have a proper description. Please tell the customer that it is a coupon code and can be redeemed only on site. Also change the year to 2018.

**Comment by JunYuZhouNoBB** [comment]
i fixed it!
